using System;
using System.Security;

int main()
{
    try
    {
        User user = GetUser(0);
        Console.Out() << user.Name() << endl();
    }
    catch (const Exception& ex)
    {
        Console.Error() << ex.Message() << endl();
        return 1;
    }
    return 0;
}